# Claude Wrapper Configuration Example
# Copy this file to ~/.claude-wrapper.yml and customize

# Path to the real Claude CLI binary (renamed to claude-original during installation)
claudePath: /usr/local/bin/claude-original

# OAuth configuration
oauth:
  # Anthropic OAuth token endpoint
  tokenUrl: https://api.anthropic.com/v1/oauth/token
  # Anthropic Console OAuth Client ID
  clientId: 9d1c250a-e61b-44d9-88ed-5944d1962f5e
  # OAuth scopes (optional, defaults to user:inference)
  scopes:
    - user:inference

# Logging configuration (optional)
logging:
  # Log level: trace, debug, info, warn, error
  level: info
  # Automatically redact sensitive tokens from logs
  redactTokens: true
  # Optional: log to file instead of stdout
  # file: ~/.claude-wrapper/logs/wrapper.log

# Refresh threshold: refresh tokens this many seconds before expiry (default: 300)
# This ensures your token is always fresh
refreshThreshold: 300

# Rate limiting configuration (optional)
# Prevents abuse and protects shared OAuth endpoints
rateLimiting:
  # Enable rate limiting (default: true)
  enabled: true
  # Maximum number of refresh attempts allowed in the bucket (default: 10)
  maxTokens: 10
  # Rate at which tokens refill (default: 1 per minute)
  refillRate: 1
  # Interval for refilling tokens in milliseconds (default: 60000 = 1 minute)
  refillInterval: 60000
